export const SERVICE_CATEGORY_ORDER = [
  'Roadside emergency',
  'Mechanical & repairs',
  'Engine & tuning',
  'Electrical & electronics',
  'Suspension & alignment',
  'Body & paint',
  'Air conditioning',
  'Cleaning & detailing',
  'Fuel & fluids',
  'Vehicle inspection',
  'Vehicle specialisation',
];

export const CATEGORY_BY_CODE: Record<string, string> = {
  towing: 'Roadside emergency',
  battery_jump_start: 'Roadside emergency',
  tyre_change: 'Roadside emergency',
  lockout_assistance: 'Roadside emergency',
  fuel_delivery: 'Roadside emergency',
  winching: 'Roadside emergency',
  fuel_petrol_regular: 'Fuel & fluids',
  fuel_petrol_premium: 'Fuel & fluids',
  fuel_diesel: 'Fuel & fluids',
  fluid_top_up: 'Fuel & fluids',
  on_site_diagnosis: 'Mechanical & repairs',
  oil_change: 'Mechanical & repairs',
  minor_repairs: 'Mechanical & repairs',
  tyre_fitting: 'Mechanical & repairs',
  brake_pad_replacement: 'Mechanical & repairs',
  brake_disc_replacement: 'Mechanical & repairs',
  brake_fluid_flush: 'Mechanical & repairs',
  clutch_replacement: 'Mechanical & repairs',
  gearbox_service: 'Mechanical & repairs',
  cv_joint_replacement: 'Mechanical & repairs',
  timing_belt_service: 'Mechanical & repairs',
  radiator_service: 'Mechanical & repairs',
  full_engine_service: 'Engine & tuning',
  ecu_remap: 'Engine & tuning',
  turbo_service: 'Engine & tuning',
  exhaust_service: 'Engine & tuning',
  air_intake_service: 'Engine & tuning',
  engine_rebuild: 'Engine & tuning',
  electrical_diagnosis: 'Electrical & electronics',
  battery_replacement: 'Electrical & electronics',
  alternator_repair: 'Electrical & electronics',
  car_audio_install: 'Electrical & electronics',
  camera_alarm_install: 'Electrical & electronics',
  lighting_upgrade: 'Electrical & electronics',
  dent_repair: 'Body & paint',
  scratch_repair: 'Body & paint',
  panel_beating: 'Body & paint',
  full_respray: 'Body & paint',
  windscreen_service: 'Body & paint',
  rust_treatment: 'Body & paint',
  wheel_alignment: 'Suspension & alignment',
  wheel_balancing: 'Suspension & alignment',
  shock_absorber_service: 'Suspension & alignment',
  suspension_service: 'Suspension & alignment',
  rim_repair: 'Suspension & alignment',
  ac_regas: 'Air conditioning',
  ac_repair: 'Air conditioning',
  cabin_filter_replacement: 'Air conditioning',
  car_wash_exterior: 'Cleaning & detailing',
  car_wash_full: 'Cleaning & detailing',
  detailing: 'Cleaning & detailing',
  engine_bay_clean: 'Cleaning & detailing',
  ceramic_coating: 'Cleaning & detailing',
  ppf_wrap: 'Cleaning & detailing',
  pre_purchase_inspection: 'Vehicle inspection',
  roadworthy_inspection: 'Vehicle inspection',
  insurance_inspection: 'Vehicle inspection',
  spec_toyota: 'Vehicle specialisation',
  spec_nissan: 'Vehicle specialisation',
  spec_subaru: 'Vehicle specialisation',
  spec_bmw: 'Vehicle specialisation',
  spec_mercedes: 'Vehicle specialisation',
  spec_land_rover: 'Vehicle specialisation',
  spec_vw_group: 'Vehicle specialisation',
  spec_japanese: 'Vehicle specialisation',
  spec_european: 'Vehicle specialisation',
  spec_ev: 'Vehicle specialisation',
};

export const serviceTypeOptions = [
  { code: 'battery_jump', label: 'Battery Jump', short: 'Power restart' },
  { code: 'fuel_delivery', label: 'Fuel Delivery', short: 'Fuel plus delivery' },
  { code: 'tire_change', label: 'Tire Change', short: 'Wheel support' },
  { code: 'towing', label: 'Towing', short: 'Recovery move' },
  { code: 'lockout', label: 'Lockout', short: 'Entry support' },
];
