export const VEHICLE_MAKES = [
  'Audi', 'BMW', 'BYD', 'Chevrolet', 'Chrysler', 'Citroën', 'Daihatsu',
  'Dodge', 'Ferrari', 'Fiat', 'Ford', 'Genesis', 'GMC', 'Honda',
  'Hyundai', 'Infiniti', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover',
  'Lexus', 'Maserati', 'Mazda', 'Mercedes-Benz', 'Mini', 'Mitsubishi',
  'Nissan', 'Peugeot', 'Porsche', 'Ram', 'Renault', 'Subaru', 'Suzuki',
  'Tesla', 'Toyota', 'Volkswagen', 'Volvo',
];

export const VEHICLE_MODELS = {
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'e-tron', 'RS3', 'RS6', 'S3', 'S4'],
  'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'M2', 'M3', 'M4', 'M5', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'iX', 'i4'],
  'BYD': ['Atto 3', 'Han', 'Seal', 'Tang', 'Dolphin', 'Seagull'],
  'Chevrolet': ['Blazer', 'Camaro', 'Colorado', 'Cruze', 'Equinox', 'Malibu', 'Silverado', 'Spark', 'Suburban', 'Tahoe', 'Traverse', 'Trax'],
  'Chrysler': ['200', '300', 'Pacifica', 'Voyager'],
  'Citroën': ['Berlingo', 'C1', 'C3', 'C4', 'C5 Aircross', 'Jumpy', 'SpaceTourer'],
  'Daihatsu': ['Boon', 'Mira', 'Move', 'Rocky', 'Sirion', 'Terios', 'YRV'],
  'Dodge': ['Challenger', 'Charger', 'Durango', 'Grand Caravan', 'Journey', 'RAM 1500'],
  'Ferrari': ['296 GTB', '812 Superfast', 'F8 Tributo', 'Portofino', 'Roma', 'SF90 Stradale'],
  'Fiat': ['500', '500X', 'Doblo', 'Ducato', 'Panda', 'Punto', 'Tipo'],
  'Ford': ['Bronco', 'EcoSport', 'Edge', 'Escape', 'Everest', 'Explorer', 'F-150', 'Fiesta', 'Focus', 'Fusion', 'Maverick', 'Mustang', 'Puma', 'Ranger', 'Transit'],
  'Genesis': ['G70', 'G80', 'G90', 'GV70', 'GV80'],
  'GMC': ['Acadia', 'Canyon', 'Sierra', 'Terrain', 'Yukon'],
  'Honda': ['Accord', 'Amaze', 'BR-V', 'City', 'Civic', 'CR-V', 'Fit / Jazz', 'Freed', 'HR-V / Vezel', 'Insight', 'Legend', 'Mobilio', 'Odyssey', 'Pilot', 'Ridgeline', 'Stream'],
  'Hyundai': ['Accent', 'Creta / ix25', 'Elantra', 'i10', 'i20', 'i30', 'Ioniq 5', 'Ioniq 6', 'Kona', 'Santa Fe', 'Sonata', 'Staria', 'Tucson', 'Venue'],
  'Infiniti': ['Q50', 'Q60', 'QX50', 'QX55', 'QX60', 'QX80'],
  'Isuzu': ['D-Max', 'Elf', 'MU-X', 'Rodeo', 'Trooper'],
  'Jaguar': ['E-Pace', 'F-Pace', 'F-Type', 'I-Pace', 'XE', 'XF', 'XJ'],
  'Jeep': ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Renegade', 'Wrangler'],
  'Kia': ['Carnival', 'Carens', 'Cerato / Forte', 'EV6', 'Niro', 'Picanto', 'Rio', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Stonic', 'Telluride'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
  'Lexus': ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RX', 'UX'],
  'Maserati': ['Ghibli', 'Grecale', 'Levante', 'MC20', 'Quattroporte'],
  'Mazda': ['BT-50', 'CX-3', 'CX-30', 'CX-5', 'CX-7', 'CX-8', 'CX-9', 'Demio / Mazda2', 'Mazda2', 'Mazda3', 'Mazda6 / Atenza', 'MX-5 Miata', 'MPV'],
  'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLK', 'GLS', 'ML-Class', 'S-Class', 'Sprinter', 'V-Class', 'Vito'],
  'Mini': ['Clubman', 'Convertible', 'Cooper', 'Countryman', 'Paceman'],
  'Mitsubishi': ['ASX / RVR', 'Attrage', 'Colt', 'Eclipse Cross', 'Galant', 'Grandis', 'L200 / Triton', 'Lancer', 'Mirage', 'Outlander', 'Pajero / Shogun', 'Pajero Sport'],
  'Nissan': ['Armada', 'Frontier', 'GT-R', 'Juke', 'Kicks', 'Leaf', 'March / Micra', 'Murano', 'Navara', 'Note', 'Pathfinder', 'Patrol', 'Qashqai', 'Rogue', 'Sentra / Sunny', 'Tiida', 'Titan', 'X-Trail'],
  'Peugeot': ['2008', '208', '3008', '308', '408', '5008', '508', 'Boxer', 'Expert', 'Partner'],
  'Porsche': ['718 Boxster', '718 Cayman', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
  'Ram': ['1500', '2500', '3500', 'ProMaster'],
  'Renault': ['Captur', 'Clio', 'Duster', 'Kadjar', 'Koleos', 'Logan', 'Megane', 'Sandero', 'Scenic', 'Trafic', 'Triber'],
  'Subaru': ['BRZ', 'Forester', 'Impreza', 'Legacy', 'Levorg', 'Outback', 'WRX', 'XV / Crosstrek'],
  'Suzuki': ['Alto', 'Baleno', 'Celerio', 'Ertiga', 'Grand Vitara', 'Ignis', 'Jimny', 'S-Cross', 'Swift', 'SX4', 'Vitara'],
  'Tesla': ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y'],
  'Toyota': ['4Runner', 'Allion', 'Alphard', 'Avalon', 'Avanza', 'Axio / Corolla Axio', 'Aygo', 'C-HR', 'Camry', 'Corolla', 'Fielder / Corolla Fielder', 'FJ Cruiser', 'Fortuner', 'GR86', 'Harrier', 'Hiace', 'Hilux', 'Innova', 'Land Cruiser', 'Land Cruiser Prado', 'Noah / Voxy', 'Prius', 'Probox', 'RAV4', 'Rush', 'Sequoia', 'Sienna', 'Succeed', 'Supra', 'Tacoma', 'Tundra', 'Vitz / Yaris', 'Wish'],
  'Volkswagen': ['Amarok', 'Arteon', 'Atlas', 'Caddy', 'Golf', 'ID.3', 'ID.4', 'Jetta / Bora', 'Passat', 'Polo', 'Sharan', 'T-Cross', 'T-Roc', 'Taos', 'Tiguan', 'Touareg', 'Touran', 'Transporter'],
  'Volvo': ['C40', 'S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
};

const currentYear = new Date().getFullYear();
export const VEHICLE_YEARS = Array.from(
  { length: currentYear - 1979 },
  (_, i) => currentYear - i,
);
